// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdaHXAA580ZUAf85zmznUt7BvKa1vmWQ',
    appId: '1:801046060474:web:1e66fed38d908eb1e71183',
    messagingSenderId: '801046060474',
    projectId: 'flutter-blog-9763b',
    authDomain: 'flutter-blog-9763b.firebaseapp.com',
    storageBucket: 'flutter-blog-9763b.appspot.com',
    measurementId: 'G-D2WVKY0ZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuBWY1fUVjh9mh870Oct7-aIPFqWx-ncU',
    appId: '1:801046060474:android:c2df1e8a58c6aec1e71183',
    messagingSenderId: '801046060474',
    projectId: 'flutter-blog-9763b',
    storageBucket: 'flutter-blog-9763b.appspot.com',
  );
}
